### ISSUE TITLE
Debug Info Remover Optimizations

### ISSUE THREAD

**Issue by Tigermouthbear** [DarkiBoi/kul#3]
make debug info remover skip excluded classes bc it can break libraries and mixins

**Comment by DarkiBoi** [comment]
huh? it should

**Comment by Tigermouthbear** [comment]
oh, youre not even reading excluded classes. You need to read the excluded classes as you will need them for method renaming and other transformers

**Comment by DarkiBoi** [comment]
oh, right

**Comment by DarkiBoi** [comment]
alright i will fix this soon

**Comment by DarkiBoi** [comment]
@Tigermouthbear Fixed the issue, look at latest commit

**Comment by Tigermouthbear** [comment]
epic
